# Generated by Django 5.2.1 on 2025-05-21 12:38

import django.db.models.deletion
import ejecutor.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutableCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Categoría de Ejecutable",
                "verbose_name_plural": "Categorías de Ejecutables",
            },
        ),
        migrations.CreateModel(
            name="ExecutableFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=ejecutor.models.executable_file_path,
                        verbose_name="Archivo Ejecutable",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Ruta del Archivo"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("uploaded", "Archivo Subido"),
                            ("preinstalled", "Preinstalado en Servidor"),
                        ],
                        default="uploaded",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "upload_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Subida"
                    ),
                ),
                (
                    "last_executed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última Ejecución"
                    ),
                ),
                (
                    "execution_count",
                    models.IntegerField(
                        default=0, verbose_name="Número de Ejecuciones"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "command_args",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Argumentos de Ejecución",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ejecutor.executablecategory",
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Subido por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivo Ejecutable",
                "verbose_name_plural": "Archivos Ejecutables",
            },
        ),
        migrations.CreateModel(
            name="ExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "execution_uuid",
                    models.CharField(
                        max_length=36, unique=True, verbose_name="ID de Ejecución"
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Ejecución"
                    ),
                ),
                (
                    "success",
                    models.BooleanField(blank=True, null=True, verbose_name="Éxito"),
                ),
                ("output", models.TextField(blank=True, verbose_name="Salida")),
                (
                    "exit_code",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Código de Salida"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                (
                    "is_realtime",
                    models.BooleanField(
                        default=False, verbose_name="Visualización en tiempo real"
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(
                        default=False, verbose_name="Ejecución completada"
                    ),
                ),
                (
                    "executable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ejecutor.executablefile",
                        verbose_name="Archivo Ejecutable",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Ejecución",
                "verbose_name_plural": "Registros de Ejecuciones",
            },
        ),
    ]
