# Generated by Django 5.2.1 on 2025-05-25 15:32

import ejecutor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ejecutor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="executablefile",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=ejecutor.models.executable_file_path,
                verbose_name="Archivo",
            ),
        ),
        migrations.AlterField(
            model_name="executablefile",
            name="file_path",
            field=models.CharField(max_length=500, verbose_name="Ruta del Archivo"),
        ),
        migrations.AlterField(
            model_name="executablefile",
            name="type",
            field=models.CharField(
                choices=[("uploaded", "Subido"), ("preinstalled", "Pre-instalado")],
                default="uploaded",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]
